apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: fastapi-accelerator
  name: fastapi-accelerator
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: fastapi-accelerator
  sessionAffinity: None
  type: NodePort
